spring:
  profiles:
    active: dev
    
---
spring:
      profiles: dev
      application:
          name:  microservicecloud-config1-dev
          
---
spring:
      profiles: test
      application:
          name:  microservicecloud-config2-test
    
